[build]
  publish = "dist"
  command = "npm run build"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[redirects]]
  from = "/homes/*"
  to = "/homes/startup"
  status = 200
  force = true
  conditions = {Role = ["dimensiones"]}
[[redirects]]
  from = "/homes/*"
  to = "/autodiagnostico-dimensiones"
  status = 302
  force = true
